version: '2'

services:

    web:
        image: dr4g0nsr/nginx-php-redis:latest
        hostname: web
        container_name: web
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - "./etc/ssl:/etc/ssl"
            - "/var/www/html:/var/www/html"
            - "./log:/var/log/nginx"
            - "/etc/letsencrypt:/etc/letsencrypt:ro"
            - "./etc/nginx:/etc/nginx/sites-enabled"
        ports:
            - "80:80"
            - "443:443"
        stop_grace_period: 5s
        restart: unless-stopped
        stdin_open: true
        tty: true
        
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        hostname: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./config/mysql:/etc/mysql/conf.d"
            - "./log:/var/log/mysql"
        restart: unless-stopped
        stdin_open: true
        tty: true

