version: '2'

services:

    web:
        image: dr4g0nsr/nginx-php-redis:latest
        hostname: web
        container_name: web
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - "./etc/ssl:/etc/ssl"
            - "/var/www/html:/var/www/html"
            - "./log:/var/log/nginx"
            - "/etc/letsencrypt:/etc/letsencrypt:ro"
            - "./etc/nginx:/etc/nginx/sites-enabled"
        ports:
            - "80:80"
            - "443:443"
        stop_grace_period: 5s
        restart: unless-stopped
        stdin_open: true
        tty: true
